// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// baum_welch_cpp
List baum_welch_cpp(NumericMatrix B, IntegerVector starts, IntegerVector ends, NumericVector initial, NumericMatrix transition, int max_iter, double tolerance, bool return_posterior);
RcppExport SEXP _CGMmfpt_baum_welch_cpp(SEXP BSEXP, SEXP startsSEXP, SEXP endsSEXP, SEXP initialSEXP, SEXP transitionSEXP, SEXP max_iterSEXP, SEXP toleranceSEXP, SEXP return_posteriorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ends(endsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type transition(transitionSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< bool >::type return_posterior(return_posteriorSEXP);
    rcpp_result_gen = Rcpp::wrap(baum_welch_cpp(B, starts, ends, initial, transition, max_iter, tolerance, return_posterior));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CGMmfpt_baum_welch_cpp", (DL_FUNC) &_CGMmfpt_baum_welch_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_CGMmfpt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
