# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

baum_welch_cpp <- function(B, starts, ends, initial, transition, max_iter = 50L, tolerance = 1e-4, return_posterior = FALSE) {
    .Call(`_CGMmfpt_baum_welch_cpp`, B, starts, ends, initial, transition, max_iter, tolerance, return_posterior)
}

